version: "3.9"
services:
  test:
    image: "lab2"
    volumes:
      - .:/lab2-test
    command: python3 -m pytest
  run:
    image: "lab2"
    volumes:
      - .:/lab2-test
    command: python3 main2.py