version: "3.9"
services:
  test:
    image: "lab3"
    volumes:
      - .:/lab3-test
    command: python3 -m pytest
  run:
    image: "lab3"
    volumes:
      - .:/lab3-test
    command: python3 main.py